"""
engines/test_case_generator.py — GuardianAI Autonomous QA  (v2)
Test Case Generator: converts FlowDefinition objects into structured QA test cases
with Playwright-executable Python snippets.

KEY CHANGES v2:
  - _generate_playwright_snippet() produces fully executable async Python code.
    No TODO comments. No missing selectors.
  - Selectors from flow_discovery v2 (element_selector field) are used directly.
    For nav flows, :has-text() selectors are parsed into get_by_role() calls.
  - For fill actions: page.fill(selector, value) with the exact selector from flow.
  - For submit actions: looks for button[type="submit"] first, then by label text.
  - Proper wait_for_load_state() after navigation and clicks.
  - JS error detection wired into every test.
  - Each test file is self-contained and runnable with: python test_file.py
"""

from __future__ import annotations

import re
import logging
from dataclasses import dataclass, field
from typing import Optional
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# ── Data Structures ────────────────────────────────────────────────────────────

@dataclass
class TestStep:
    step_number: int
    description: str
    action: str          # navigate|fill|click|submit|assert|wait
    target: Optional[str] = None   # CSS selector or URL
    value: Optional[str] = None    # value to type (fill action)


@dataclass
class TestCase:
    tc_id: str
    flow_id: str
    scenario: str
    description: str
    preconditions: list[str]
    steps: list[TestStep]
    expected_result: str
    actual_result: Optional[str] = None
    status: str = "pending"
    severity: str = "medium"
    playwright_snippet: Optional[str] = None
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "tc_id":             self.tc_id,
            "flow_id":           self.flow_id,
            "scenario":          self.scenario,
            "description":       self.description,
            "preconditions":     self.preconditions,
            "expected_result":   self.expected_result,
            "actual_result":     self.actual_result,
            "status":            self.status,
            "severity":          self.severity,
            "playwright_snippet": self.playwright_snippet,
            "tags":              self.tags,
            "steps": [
                {
                    "step_number": s.step_number,
                    "description": s.description,
                    "action":      s.action,
                    "target":      s.target,
                    "value":       s.value,
                }
                for s in self.steps
            ],
        }


# ── Playwright Snippet Generator ───────────────────────────────────────────────

def _extract_has_text(selector: str) -> Optional[str]:
    """
    Extracts the text value from a :has-text("...") selector.
    Returns None if the pattern is not found.
    """
    m = re.search(r':has-text\("([^"]+)"\)', selector)
    if m:
        return m.group(1)
    m = re.search(r":has-text\('([^']+)'\)", selector)
    if m:
        return m.group(1)
    return None


def _generate_playwright_snippet(tc: "TestCase", flow: dict) -> str:
    """
    Generates a runnable async Playwright Python test from a TestCase.

    Design goals:
      - Zero TODO comments
      - All selectors resolved to actual Playwright API calls
      - Self-contained: can be run with `python <file>.py`
      - Includes JS error detection
      - Uses page.get_by_role() where possible (most readable)
      - Falls back to page.locator() for ID/name/complex selectors
    """
    fn_name = tc.tc_id.lower().replace("-", "_")
    entry_url = flow.get("entry_url", "")

    lines = [
        f"# {tc.tc_id}: {tc.scenario}",
        f"# Severity: {tc.severity}",
        f"# Generated by Guardian AI — paste into your Playwright test suite",
        f"# Run standalone: python -c \"import asyncio; from {fn_name} import {fn_name}; asyncio.run({fn_name}())\"",
        "",
        "import asyncio",
        "from playwright.async_api import async_playwright, expect",
        "",
        "",
        f"async def {fn_name}():",
        f'    """',
        f"    {tc.scenario}",
        f"    {tc.description or ''}",
        f"    Expected: {tc.expected_result}",
        f'    """',
        "    async with async_playwright() as p:",
        "        browser = await p.chromium.launch(headless=True)",
        "        page = await browser.new_page()",
        "        page.set_default_timeout(15000)",
        "",
        "        # Capture JavaScript errors",
        "        js_errors = []",
        "        page.on('pageerror', lambda e: js_errors.append({'message': str(e), 'stack': getattr(e, 'stack', None)}))",
        "        page.on('console', lambda m: js_errors.append({'message': m.text, 'source': 'console'}) if m.type == 'error' else None)",
        "",
    ]

    for step in tc.steps:
        action  = step.action
        target  = step.target   # selector from flow_discovery (already computed)
        value   = step.value
        desc    = step.description

        lines.append(f"        # Step {step.step_number}: {desc}")

        if action == "navigate":
            url = entry_url or (target if target and target.startswith("http") else "")
            lines.append(f'        response = await page.goto("{url}", wait_until="domcontentloaded")')
            lines.append(f'        assert response.status < 400, f"HTTP {{response.status}} on {url}"')
            lines.append(f'        await page.wait_for_load_state("networkidle")')

        elif action in ("click", "submit"):
            if target:
                link_text = _extract_has_text(target)
                if link_text:
                    # :has-text() selector → use get_by_role for readability
                    safe = link_text.replace('"', '\\"')
                    if "menuitem" in target:
                        lines.append(f'        await page.get_by_role("menuitem", name="{safe}").click()')
                    else:
                        lines.append(
                            f'        # Try role-based selector first, fall back to text match\n'
                            f'        try:\n'
                            f'            await page.get_by_role("link", name="{safe}").click()\n'
                            f'        except Exception:\n'
                            f'            await page.get_by_text("{safe}").first.click()'
                        )
                elif target.startswith("#") or target.startswith("["):
                    lines.append(f'        await page.locator("{target}").click()')
                elif "submit" in target:
                    lines.append(f'        await page.locator("{target}").first.click()')
                else:
                    lines.append(f'        await page.locator("{target}").first.click()')
            else:
                # No selector: try common submit button patterns
                lines.append(
                    '        # Locate submit button\n'
                    '        submit_btn = page.locator(\'button[type="submit"], input[type="submit"]\')\n'
                    '        if await submit_btn.count() > 0:\n'
                    '            await submit_btn.first.click()\n'
                    '        else:\n'
                    '            await page.locator("button").last.click()'
                )
            lines.append('        await page.wait_for_load_state("networkidle")')

        elif action == "fill":
            if target and value:
                if target.startswith("#"):
                    lines.append(f'        await page.locator("{target}").fill("{value}")')
                elif target.startswith("[name="):
                    lines.append(f'        await page.locator("{target}").fill("{value}")')
                elif "placeholder" in target or "aria-label" in target:
                    lines.append(f'        await page.locator("{target}").first.fill("{value}")')
                else:
                    lines.append(f'        await page.locator("{target}").fill("{value}")')
            elif value:
                # No selector but we have a value: try by label text
                lines.append(f'        # Fill field for: {desc}')
                label_hint = desc.split(":")[0] if ":" in desc else desc
                lines.append(f'        await page.get_by_label("{label_hint}").fill("{value}")')

        elif action == "assert":
            if target:
                lines.append(f'        await expect(page.locator("{target}")).to_be_visible()')
            else:
                lines.append(f'        # Assert: {desc}')
                lines.append(f'        assert await page.locator("body").is_visible(), "Page body not visible"')

        # Expected outcome as assertion comment
        if step.action not in ("navigate",) and hasattr(step, "expected_outcome"):
            pass  # expected_outcome lives on FlowStep, not TestStep — skip

        lines.append("")

    lines += [
        "        # ── Post-test assertions ──────────────────────────────────────────",
        '        final_url = page.url',
        '        assert final_url, "No final URL — navigation may have failed"',
        "",
        "        # Fail on JS errors (comment out if intentional JS errors are expected)",
        '        assert len(js_errors) == 0, f"JavaScript errors detected: {js_errors}"',
        "",
        "        await browser.close()",
        "",
        "",
        f"if __name__ == '__main__':",
        f"    asyncio.run({fn_name}())",
    ]

    return "\n".join(lines)


# ── Test Step Builder ──────────────────────────────────────────────────────────

def _build_test_steps(flow_dict: dict) -> list[TestStep]:
    """
    Converts FlowDefinition steps (dicts) to TestStep objects.
    Preserves the element_selector from flow_discovery as step.target.
    Extracts fill values from action_detail strings like "Enter email: 'foo@bar.com'".
    """
    test_steps = []
    for s in flow_dict.get("steps") or []:
        action_map = {
            "navigate":  "navigate",
            "fill_form": "fill",
            "click":     "click",
            "submit":    "submit",
        }
        action = action_map.get(s.get("action"), "navigate")

        # element_selector from flow_discovery is our primary selector
        target = s.get("element_selector")

        # For navigate steps, use the page URL as the target
        if action == "navigate" and not target:
            target = s.get("page_url", "")

        value = None
        detail = s.get("action_detail") or ""

        # Extract fill value from patterns like "Enter label: 'value'"
        if action == "fill" and "'" in detail:
            # Match: Enter SomeLabel: 'theValue'
            m = re.search(r"'([^']+)'", detail)
            if m:
                value = m.group(1)

        test_steps.append(TestStep(
            step_number=s["step_number"],
            description=detail,
            action=action,
            target=target,
            value=value,
        ))

    return test_steps


# ── Severity + Precondition Maps ───────────────────────────────────────────────

_SEVERITY_MAP = {
    "login":          "critical",
    "registration":   "critical",
    "checkout":       "critical",
    "cart":           "high",
    "shop":           "high",
    "dashboard":      "high",
    "password_reset": "high",
    "search":         "medium",
    "contact":        "medium",
    "profile":        "medium",
    "navigation":     "medium",
    "newsletter":     "low",
    "generic_form":   "medium",
}

_PRECONDITIONS_MAP = {
    "login": [
        "Application is accessible and running",
        "A valid user account exists in the system",
        "User is not currently logged in",
    ],
    "registration": [
        "Application is accessible and running",
        "Registration is open (not invite-only)",
        "Email address used for test does not already exist",
    ],
    "checkout": [
        "Application is accessible and running",
        "User is logged in with a valid account",
        "At least one product is available for purchase",
        "Cart contains at least one item",
    ],
    "search": [
        "Application is accessible and running",
        "At least one indexed item exists to search for",
    ],
    "contact": [
        "Application is accessible and running",
        "Contact form is enabled and email service is configured",
    ],
    "navigation": [
        "Application is accessible and running",
        "User has access to the pages in this flow",
    ],
}


# ── Main Entry Point ───────────────────────────────────────────────────────────

def generate_test_cases(flows: list[dict], run_id: int) -> list[TestCase]:
    """
    Main entry point. Accepts flow dicts (from discover_flows_as_dicts)
    and returns a list of TestCase objects with executable Playwright snippets.
    """
    test_cases: list[TestCase] = []

    for i, flow in enumerate(flows, 1):
        tc_id     = f"TC-{run_id}-{i:03d}"
        flow_type = flow.get("flow_type", "navigation")
        severity  = _SEVERITY_MAP.get(flow_type, "medium")
        preconditions = _PRECONDITIONS_MAP.get(flow_type, [
            "Application is accessible and running",
        ])

        steps = _build_test_steps(flow)

        last_step_raw = (flow.get("steps") or [{}])[-1]
        expected = (
            last_step_raw.get("expected_outcome")
            or f"{flow['flow_name']} completes successfully without errors"
        )

        tc = TestCase(
            tc_id=tc_id,
            flow_id=flow["flow_id"],
            scenario=flow["flow_name"],
            description=flow.get("description", ""),
            preconditions=preconditions,
            steps=steps,
            expected_result=expected,
            severity=severity,
            status="pending",
            tags=flow.get("tags", []) + [flow_type],
        )

        # Generate the executable Playwright snippet
        tc.playwright_snippet = _generate_playwright_snippet(tc, flow)

        test_cases.append(tc)

    logger.info(
        f"[test_case_generator] Generated {len(test_cases)} test cases "
        f"from {len(flows)} flows for run {run_id}"
    )
    return test_cases


def generate_test_cases_as_dicts(flows: list[dict], run_id: int) -> list[dict]:
    """Convenience wrapper returning plain dicts for JSON serialisation."""
    return [tc.to_dict() for tc in generate_test_cases(flows, run_id)]