"""
engines/test_case_generator.py — GuardianAI Autonomous QA
Test Case Generator: converts FlowDefinition objects into structured QA test cases
with Playwright-executable snippets.

No new crawl infrastructure — consumes FlowDefinition from flow_discovery.py.
"""

from __future__ import annotations

import textwrap
import logging
from dataclasses import dataclass, field
from typing import Optional
from urllib.parse import urlparse

logger = logging.getLogger(__name__)


# ── Data Structures ────────────────────────────────────────────────────────────

@dataclass
class TestStep:
    step_number: int
    description: str
    action: str          # navigate|fill|click|submit|assert|wait
    target: Optional[str] = None   # selector or URL
    value: Optional[str] = None    # value to type


@dataclass
class TestCase:
    tc_id: str                    # e.g. "TC-001"
    flow_id: str
    scenario: str
    description: str
    preconditions: list[str]
    steps: list[TestStep]
    expected_result: str
    actual_result: Optional[str] = None     # filled during execution
    status: str = "pending"                 # pending|pass|fail|blocked|skipped
    severity: str = "medium"               # critical|high|medium|low
    playwright_snippet: Optional[str] = None
    tags: list[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "tc_id":             self.tc_id,
            "flow_id":           self.flow_id,
            "scenario":          self.scenario,
            "description":       self.description,
            "preconditions":     self.preconditions,
            "expected_result":   self.expected_result,
            "actual_result":     self.actual_result,
            "status":            self.status,
            "severity":          self.severity,
            "playwright_snippet": self.playwright_snippet,
            "tags":              self.tags,
            "steps": [
                {
                    "step_number": s.step_number,
                    "description": s.description,
                    "action":      s.action,
                    "target":      s.target,
                    "value":       s.value,
                }
                for s in self.steps
            ],
        }


# ── Playwright Snippet Generator ───────────────────────────────────────────────

def _generate_playwright_snippet(tc: "TestCase", flow: dict) -> str:
    """
    Generates a runnable async Playwright Python snippet from a test case.
    Developers can paste this directly into their test suite.
    """
    lines = [
        f"# {tc.tc_id}: {tc.scenario}",
        f"# Generated by Guardian AI — copy into your Playwright test suite",
        "",
        "import asyncio",
        "from playwright.async_api import async_playwright, expect",
        "",
        f"async def {tc.tc_id.lower().replace('-', '_')}():",
        '    """',
        f'    {tc.scenario}',
        f'    Expected: {tc.expected_result}',
        '    """',
        "    async with async_playwright() as p:",
        "        browser = await p.chromium.launch(headless=True)",
        "        page = await browser.new_page()",
        "        page.set_default_timeout(10000)",
        "        errors = []",
        "        page.on('pageerror', lambda e: errors.append(str(e)))",
        "",
    ]

    for step in tc.steps:
        lines.append(f"        # Step {step.step_number}: {step.description}")
        if step.action == "navigate":
            target = step.target or flow.get("entry_url", "")
            lines.append(f'        response = await page.goto("{target}", wait_until="domcontentloaded")')
            lines.append(f'        assert response.status < 400, f"Got {{response.status}} on {target}"')
        elif step.action == "fill":
            if step.target and step.value:
                lines.append(f'        await page.fill("{step.target}", "{step.value}")')
        elif step.action in ("click", "submit"):
            if step.target:
                lines.append(f'        await page.click("{step.target}")')
                lines.append(f'        await page.wait_for_load_state("networkidle")')
            else:
                lines.append(f'        # TODO: identify submit selector manually')
        elif step.action == "assert":
            if step.target:
                lines.append(f'        await expect(page.locator("{step.target}")).to_be_visible()')
        lines.append("")

    lines += [
        "        # Validate no JS errors occurred",
        '        assert len(errors) == 0, f"JS errors: {errors}"',
        "        await browser.close()",
        "",
        "",
        f"if __name__ == '__main__':",
        f"    asyncio.run({tc.tc_id.lower().replace('-', '_')}())",
    ]

    return "\n".join(lines)


# ── Test Case Builder ──────────────────────────────────────────────────────────

_SEVERITY_MAP = {
    "login": "critical",
    "registration": "critical",
    "checkout": "critical",
    "cart": "high",
    "shop": "high",
    "dashboard": "high",
    "password_reset": "high",
    "search": "medium",
    "contact": "medium",
    "profile": "medium",
    "navigation": "medium",
    "newsletter": "low",
    "generic_form": "medium",
}

_PRECONDITIONS_MAP = {
    "login": [
        "Application is accessible and running",
        "A valid user account exists in the system",
        "User is not currently logged in",
    ],
    "registration": [
        "Application is accessible and running",
        "Registration is open (not invite-only)",
        "Email address used for test does not already exist",
    ],
    "checkout": [
        "Application is accessible and running",
        "User is logged in with a valid account",
        "At least one product is available for purchase",
        "Cart contains at least one item",
    ],
    "search": [
        "Application is accessible and running",
        "At least one indexed item exists to search for",
    ],
    "contact": [
        "Application is accessible and running",
        "Contact form is enabled and email service is configured",
    ],
}


def _build_test_steps(flow_dict: dict) -> list[TestStep]:
    """Converts flow steps to TestStep objects with Playwright-compatible data."""
    test_steps = []
    for s in flow_dict.get("steps") or []:
        action_map = {
            "navigate": "navigate",
            "fill_form": "fill",
            "click": "click",
            "submit": "submit",
        }
        action = action_map.get(s.get("action"), "navigate")

        target = s.get("element_selector")
        value = None

        # Extract value from action_detail ("Enter email: 'foo@bar.com'")
        detail = s.get("action_detail") or ""
        if "'" in detail and action == "fill":
            parts = detail.split("'")
            if len(parts) >= 2:
                value = parts[1]

        # For submit steps, try to build a selector
        if action == "submit" and not target:
            target = 'button[type="submit"], input[type="submit"], button:has-text("Submit")'

        test_steps.append(TestStep(
            step_number=s["step_number"],
            description=detail or s.get("action_detail") or "",
            action=action,
            target=target,
            value=value,
        ))

    return test_steps


def generate_test_cases(flows: list[dict], run_id: int) -> list[TestCase]:
    """
    Main entry point. Accepts flow dicts (from discover_flows_as_dicts)
    and returns a list of TestCase objects.

    Integration: called from tasks.py after flow discovery.
    """
    test_cases: list[TestCase] = []

    for i, flow in enumerate(flows, 1):
        tc_id = f"TC-{run_id}-{i:03d}"
        flow_type = flow.get("flow_type", "navigation")
        severity = _SEVERITY_MAP.get(flow_type, "medium")
        preconditions = _PRECONDITIONS_MAP.get(flow_type, [
            "Application is accessible and running",
        ])

        steps = _build_test_steps(flow)

        # Expected result: from the last step's expected_outcome, or default
        last_step_raw = (flow.get("steps") or [{}])[-1]
        expected = (
            last_step_raw.get("expected_outcome")
            or f"{flow['flow_name']} completes successfully without errors"
        )

        tc = TestCase(
            tc_id=tc_id,
            flow_id=flow["flow_id"],
            scenario=flow["flow_name"],
            description=flow.get("description", ""),
            preconditions=preconditions,
            steps=steps,
            expected_result=expected,
            severity=severity,
            status="pending",
            tags=flow.get("tags", []) + [flow_type],
        )

        # Generate Playwright snippet
        tc.playwright_snippet = _generate_playwright_snippet(tc, flow)

        test_cases.append(tc)

    logger.info(f"[test_case_generator] Generated {len(test_cases)} test cases from {len(flows)} flows")
    return test_cases


def generate_test_cases_as_dicts(flows: list[dict], run_id: int) -> list[dict]:
    """Convenience wrapper returning plain dicts for JSON serialisation."""
    return [tc.to_dict() for tc in generate_test_cases(flows, run_id)]